version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0.28-node-browsers
        environment:
          APP_ENV: testing
          APP_DEBUG: true
          APP_KEY: base64:H2lnWgQiH23t04sHcwDZ8VbLqQCD5J8hpVMdylqDkp0=
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testdb
          DB_USERNAME: root
          DB_PASSWORD: password
          CACHE_DRIVER: file
          QUEUE_DRIVER: sync
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: password
    working_directory: ~/laravel
    steps:
      - run:
          name: Install System Packages
          command: sudo apt-get update && sudo apt-get -y install git unzip zlib1g-dev
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install pdo pdo_mysql zip
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Install Project Dependencies
          command: php composer.phar install
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Initialize Database
          command: |
            php artisan migrate:refresh --no-interaction
            php artisan db:seed
      - run:
          name: Run Tests
          command: vendor/bin/phpunit -d memory_limit=512M
